version: '2'
services:
  mongodb:
    image: mongo:latest
    restart: always
    container_name: study-mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
